# Generated by Django 5.0.2 on 2024-03-05 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articles_options_alter_articles_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag_rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='وبلاگ من')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 18, 4, 45, 909962, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
