# Generated by Django 5.0.2 on 2024-03-05 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_rel_alter_articles_publish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag_rel',
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 41, 7, 730602, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
