# Generated by Django 5.0.2 on 2024-03-17 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_tag_rel_alter_articles_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='زیردسته'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 48, 52, 887059, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
