# Generated by Django 5.0.2 on 2024-03-17 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_parent_alter_articles_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 20, 43, 19, 441593, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
