# Generated by Django 5.0.2 on 2024-04-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_articles_auther_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='auther',
        ),
    ]
